### ISSUE TITLE
add 'make first plonk link' or show no plonks yet on initial signup

### ISSUE THREAD

**Issue by bFraley** [JasonMize/plonker#13]
![screen shot 2016-10-18 at 4 26 36 pm](https://cloud.githubusercontent.com/assets/3700154/19495040/b68ad3b4-954f-11e6-9c4f-505ae80f0095.png)

**Comment by JasonMize** [comment]
Should it start you on the "create a Plonk" page or on "The Big Pond" (news feed) page?

**Comment by bFraley** [comment]
I'd redirect to create a Plonk, so there's an immediate call to action

**Comment by bFraley** [comment]
Hi Jason! I'm doing some massive Github repo and old open issues cleanup. Cheers buddy!
